export const TodoQuery = {
  FETCH_TODO_LIST: 'FETCH_TODO_LIST',
  FETCH_TODO_LIST_FAILED: 'FETCH_TODO_LIST_FAILED',
  ADD_TODO_TASK: 'ADD_TODO_TASK',
  ADD_TODO_TASK_FAILED: 'ADD_TODO_TASK_FAILED',
  EDIT_TODO_TASK: 'EDIT_TODO_ITEM',
  EDIT_TODO_TASK_FAILED: 'EDIT_TODO_ITEM_FAILED',
  DELETE_TODO_TASK: 'DELETE_TODO_ITEM',
  DELETE_TODO_TASK_FAILED: 'DELETE_TODO_ITEM_FAILED',
  TOGGLE_TODO_STATE: 'TOGGLE_TODO_STATE',
  SEARCH: 'SEARCH'
}

export const TaskFilter = {
  SHOW_ALL: 'SHOW_ALL',
  SHOW_DONE: 'SHOW_DONE',
  SHOW_ACTIVE: 'SHOW_ACTIVE'
}

export const FilterTags = {
  all: 'all',
  active: 'active',
  done: 'done'
}
